### ISSUE TITLE
Map Design

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#21]
# Summary

Design mockups for the spike map component.

# Deliverables

@sashasashasasha  to provide static mockups that contain:

- [x] spike color options
- [x] base map style (state labels, options for city or [area of interest labels](https://www.nytimes.com/interactive/2020/04/06/us/coronavirus-deaths-united-states.html))
- [ ] example of highlighted spike or area of interest
- [ ] button toggle style
- [x] map legend
- [ ] tooltip

@Lane to implement

**Comment by Lane** [comment]
# TODO (week of Nov 9 - 14)

- [ ] example of "spike label" or area of interest labels
- [ ] button toggle style
- [ ] map legend

**Comment by Lane** [comment]
base map style implemented, #32 and #29 have been created for outstanding tasks
