### ISSUE TITLE
Vaccine Table Clarifications

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/covid-19-behind-bars#382]
## Objective
Inconsistencies in how vaccine data is reported might make our presentation of the data on the homepage misleading. The following changes are intended to help clarify this for users. 

## Tasks
- [x] **[DESIGN]** Define flag color, size and placement
- [x] **[DESIGN]** Tooltip design (font family, size, and color; background color and opacity) 
- [x] Remove "Total" columns, only show rates in the vaccine table
- [x] Add “flag” icons next to the 3 jurisdictions that do not report first dose numbers (BOP, Maine, South Carolina).  When the user hovers / clicks the jurisdiction icon, show a tooltip explaining that only fully vaccinated numbers are available 
- [x] Update the note under the table to callout the 3 jurisdictions that are only showing full dose numbers. 

## Reference
[Context doc](https://docs.google.com/document/d/1OrZjknc623tWWAy8dGWhSovI223OVJ8wdfExiuQIpGI/edit?usp=sharing) - we're moving forward with the first proposed solution

[Find copy here](https://docs.google.com/document/d/12foznOz_zuT74NmQd0ouIWmpiA3HBzV-_ON22L9rTS4/edit#)

[Finalized designs here](https://www.figma.com/file/TKdSksUXJjYDl9FePrEiZz/UCLA-CBB-Style-guide-Site-map?node-id=1130%3A38)

**Comment by ekmason** [comment]
## Internal QA - Round Feedback
- [ ] Update data notes to reflect [copy doc](https://docs.google.com/document/d/12foznOz_zuT74NmQd0ouIWmpiA3HBzV-_ON22L9rTS4/edit#)
- [ ] Update paragraph next to vaccine table to reflect copy in doc linked above
- [ ] Update section title to "COVID-19 Vaccines in State and Federal Prisons"

**Comment by ekmason** [comment]
## Additional changes requested from UCLA
- Add flag to Arizona
- Update column header copy to reference "Vaccination Rate" instead of "Vaccine Rate" 
- Where data isn't available, display `--` instead of `N/A`

**Comment by Lane** [comment]
changes live on staging

**Comment by Lane** [comment]
@ekmason good to close out this issue?
