### ISSUE TITLE
Revised summary section on state pages

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#418]
# Current Behaviour

On state pages, currently the top two sections (Incarcerated people + staff) show an aggregate total of counts / rates for the given state.  These totals are aggregates, and are not tied to the facility map to the right.

# Desired Behaviour

There should be one section at the top that covers aggregate data for the state, showing totals for all metrics + populations.  The map should be removed from this section, and only be displayed on the "facilities" section.

In addition to condensing this section into a single section, the rates should be updated to `x` per 10k instead of a % using the provided population values.

# Tasks

- [x] create mockup for summary section (@Lane)
- [x] get client approval (@ekmason)
- [x] implementation (WIP: #437)
- [x] update homepage facilities table to use same heading structure / metrics as summary table (TBD)

**Comment by Lane** [comment]
@ekmason updated the mockups based on their requested revisions:

![state-page-revised2](https://user-images.githubusercontent.com/21034/125534772-3c5c026d-437c-42a7-88f1-7f5f6e6433e2.png)

**Comment by ekmason** [comment]
## Second Round Revisions (looking to confirm w/Liz that these are final revisions) 

[Reference](https://docs.google.com/document/d/19kkw1_rqnc_-XfQvqnSvcFQhBJ4u7zg7EsI4CSrUOkw/edit?pli=1)

- [ ] Adjust the category names to:
     - Incarcerated People
          - State Adult Prisons
          - Federal Prisons
          - ICE Detention Centers
          - State and Local Youth Facilities
          - State Psychiatric Facilities
     - Staff
          - State Adult Prisons
          - Federal Prisons
- [ ] Remove the word “Overall” from the Overall Data Reporting & Quality Grade
- [ ] Update copy for top of state page: 
> The table below displays aggregate COVID-19 data for incarcerated people and staff in carceral facilities located in [State]. The Data Reporting & Quality Grade to the right represents our assessment of the transparency and quality of those data reported by [State]’s state department of corrections.

**Comment by ekmason** [comment]
I've updated designs for the above (with the exception of the copy paragraph... needing to install some new fonts!), which have been approved for implementation! Ready for dev.
