### ISSUE TITLE
Add youth detention center data

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/covid-19-behind-bars#424]
## Objective
Incorporate newly available data on youth detention facilities

## Tasks
- [x] (DESIGN) Determine additional color to represent youth facilities on the map 
- [x] (DEV) Incorporate youth data
- [x] (DEV) Implement new legend color on state pages, and the homepage

**Comment by ekmason** [comment]
@sashasashasasha requirements have changed slightly - we won't be including psychiatric facility data at all! I've updated the designs to reflect this - would you review and finalize?

**Comment by ekmason** [comment]
@touchRED - designs can be found [here](https://www.figma.com/file/TKdSksUXJjYDl9FePrEiZz/UCLA-CBB-Style-guide-Site-map?node-id=2268%3A1121), we will no longer be adding psychiatric facilities, only youth detention! 

![image.png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/b0f3314a-ff9f-4818-99e3-8acc81de93cc)
