### ISSUE TITLE
Update federal aggregate counts

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#480]
The federal page should be updated to resemble the state page updates.

## Tasks

- [ ] adda script to fetch and parse the aggregate data
- [ ] add a new node containing the federal aggregate data
- [ ] pull the new aggregate data into the federal page via graphql
- [ ] remove the first two sections on the federal page and replace with the summary table used on state pages

> to get the federal level aggregate counts, pull from the [state_counts file](https://github.com/uclalawcovid19behindbars/data/blob/master/latest-data/latest_state_counts.csv) for the row where State == Federal (the denominator for the rates would be Staff.Population and Residents.Population)

**Comment by Lane** [comment]
duplicate functionality that was implemented in #544
